# Generated by Django 2.2.5 on 2019-10-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='caption',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
